---
- name: Install Azul Zulu JDK
  hosts: example_vms
  vars:
    - java_ver: 8
  tasks:
    - name: Import Azul GPG key into RPM keyring
      become: yes
      rpm_key:
        key: http://repos.azulsystems.com/RPM-GPG-KEY-azulsystems
        state: present

    - name: Add Azul JDK repo
      become: yes
      yum_repository:
        name: zulu
        description: zulu-$releasever - Azul Systems Inc., Zulu packages for $basearch
        file: zulu
        baseurl: http://repos.azulsystems.com/rhel/$releasever/$basearch
        gpgkey: http://repos.azulsystems.com/RPM-GPG-KEY-azulsystems
        gpgcheck: yes
        protect: yes
        enabled: yes

    - name: Install Java
      become: yes
      yum:
        name: "zulu-{{ java_ver }}"
        state: present
